### ISSUE TITLE
Stability derivates broken in latest release

### ISSUE THREAD

**Issue by siimav** [dkavolis/Ferram-Aerospace-Research#75]
The latest release appears to have broken the stability derivates window on KSP 1.6.1 using RSS/RO/RP-1. This issue happens with every rocket I tried to load up.

![screenshot334](https://user-images.githubusercontent.com/1120038/60924810-cc76f980-a2aa-11e9-8dfb-10aafc757220.png)

**Comment by dkavolis** [comment]
Can you give a screenshot of what it looked like in the previous release? I've changed the stability derivatives to show NaN if no stable AoA was found whereas the previous release still computed the derivatives at that AoA which was unstable (and possibly random since the root solver would not converge so the derivative values would be garbage anyway). In regards to rockets, there shouldn't be stable AoA since they don't have enough lift. IMO there should be an input for the angle at which to compute the derivatives in addition to computing them at the stable AoA.

**Comment by siimav** [comment]
Reverted the FARc version and this is what I got with the same rocket. Truth be told, I don't really care about the stability derivatives directly. What I do find important is the Static analysis to figure out at what mach values my rocket or re-entry vehicle is statically stable at.

![screenshot334](https://user-images.githubusercontent.com/1120038/60927472-c1c06280-a2b2-11e9-8c28-41860fdb9c39.png)

**Comment by dkavolis** [comment]
I can display stability derivatives at 0 AoA if there is no stable AoA found if that helps.

**Comment by siimav** [comment]
Not sure what that means. I have to ask though - why change the stability derivative system at all because it looked to be working fine before. At least previously the Static analysis tool was definitely giving meaningful values.

**Comment by Gordon-Dry** [comment]
Not sure if this is related, but when enabling one of the Transonic Design curves, a second "curve" in black appears nearby - but it's just a line (see left side of picture):
![screenshot_2019-07-14--19-09-53](https://user-images.githubusercontent.com/29145213/61186908-2e4cb000-a66b-11e9-93dc-4bdf91d2b0ab.jpg)

This did not happen in the previous build.
